name: crc_terraform_backend
on:
  push:
    branches:
      - "main"
permissions:
  id-token: write
  contents: write
  
jobs:
  Terraform_Deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: ./
    
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          role-to-assume: arn:aws:iam::053127563287:role/GithubActionsRole
          aws-region: ca-central-1
#Checkout git repository for pipeline run
      - name: checkout
        uses: actions/checkout@v3

#Install Python and run unit tests on Lambda python code
      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          pythonVersion: '3.9.0'
          cache: pip

      - run: pip install -r requirements.txt
        
      - run: python ./Lambda/tests.py 
#Install Terraform on runner vm
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4
 #Update tf state data     
      - name: Terraform Init
        id: Init
        run: terraform init
#Plan out steps to be applied with terraform
      - name: Terraform Plan
        id: Plan
        run: terraform plan
